const tarotCards = [
    // Major Arcana
    { name: 'The Fool', image: 'Placeholder for The Fool' },
    { name: 'The Magician', image: 'Placeholder for The Magician' },
    { name: 'The High Priestess', image: 'Placeholder for The High Priestess' },
    { name: 'The Empress', image: 'Placeholder for The Empress' },
    { name: 'The Emperor', image: 'Placeholder for The Emperor' },
    { name: 'The Hierophant', image: 'Placeholder for The Hierophant' },
    { name: 'The Lovers', image: 'Placeholder for The Lovers' },
    { name: 'The Chariot', image: 'Placeholder for The Chariot' },
    { name: 'Strength', image: 'Placeholder for Strength' },
    { name: 'The Hermit', image: 'Placeholder for The Hermit' },
    { name: 'Wheel of Fortune', image: 'Placeholder for Wheel of Fortune' },
    { name: 'Justice', image: 'Placeholder for Justice' },
    { name: 'The Hanged Man', image: 'Placeholder for The Hanged Man' },
    { name: 'Death', image: 'Placeholder for Death' },
    { name: 'Temperance', image: 'Placeholder for Temperance' },
    { name: 'The Devil', image: 'Placeholder for The Devil' },
    { name: 'The Tower', image: 'Placeholder for The Tower' },
    { name: 'The Star', image: 'Placeholder for The Star' },
    { name: 'The Moon', image: 'Placeholder for The Moon' },
    { name: 'The Sun', image: 'Placeholder for The Sun' },
    { name: 'Judgement', image: 'Placeholder for Judgement' },
    { name: 'The World', image: 'Placeholder for The World' },
    //Minor Arcana
    // Cups
    { name: 'Ace of Cups', image: 'Placeholder for Ace of Cups' },
    { name: 'Two of Cups', image: 'Placeholder for Two of Cups' },
    { name: 'Three of Cups', image: 'Placeholder for Three of Cups' },
    { name: 'Four of Cups', image: 'Placeholder for Four of Cups' },
    { name: 'Five of Cups', image: 'Placeholder for Five of Cups' },
    { name: 'Six of Cups', image: 'Placeholder for Six of Cups' },
    { name: 'Seven of Cups', image: 'Placeholder for Seven of Cups' },
    { name: 'Eight of Cups', image: 'Placeholder for Eight of Cups' },
    { name: 'Nine of Cups', image: 'Placeholder for Nine of Cups' },
    { name: 'Ten of Cups', image: 'Placeholder for Ten of Cups' },
    { name: 'Page of Cups', image: 'Placeholder for Page of Cups' },
    { name: 'Knight of Cups', image: 'Placeholder for Knight of Cups' },
    { name: 'Queen of Cups', image: 'Placeholder for Queen of Cups' },
    { name: 'King of Cups', image: 'Placeholder for King of Cups' },
    // Pentacles
    { name: 'Ace of Pentacles', image: 'Placeholder for Ace of Pentacles' },
    { name: 'Two of Pentacles', image: 'Placeholder for Two of Pentacles' },
    { name: 'Three of Pentacles', image: 'Placeholder for Three of Pentacles' },
    { name: 'Four of Pentacles', image: 'Placeholder for Four of Pentacles' },
    { name: 'Five of Pentacles', image: 'Placeholder for Five of CuPentaclesps' },
    { name: 'Six of Pentacles', image: 'Placeholder for Six of Pentacles' },
    { name: 'Seven of Pentacles', image: 'Placeholder for Seven of Pentacles' },
    { name: 'Eight of Pentacles', image: 'Placeholder for Eight of Pentacles' },
    { name: 'Nine of Pentacles', image: 'Placeholder for Nine of Pentacles' },
    { name: 'Ten of Pentacles', image: 'Placeholder for Ten of Pentacles' },
    { name: 'Page of Pentacles', image: 'Placeholder for Page of Pentacles' },
    { name: 'Knight of Pentacles', image: 'Placeholder for Knight of Pentacles' },
    { name: 'Queen of Pentacles', image: 'Placeholder for Queen of Pentacles' },
    { name: 'King of Pentacles', image: 'Placeholder for King of Pentacles' },
    // Swords
    { name: 'Ace of Swords', image: 'Placeholder for Ace of Swords' },
    { name: 'Two of Swords', image: 'Placeholder for Two of Swords' },
    { name: 'Three of Swords', image: 'Placeholder for Three of Swords' },
    { name: 'Four of Swords', image: 'Placeholder for Four of Swords' },
    { name: 'Five of Swords', image: 'Placeholder for Five of Swords' },
    { name: 'Six of Swords', image: 'Placeholder for Six of Swords' },
    { name: 'Seven of Swords', image: 'Placeholder for Seven of Swords' },
    { name: 'Eight of Swords', image: 'Placeholder for Eight of Swords' },
    { name: 'Nine of Swords', image: 'Placeholder for Nine of Swords' },
    { name: 'Ten of Swords', image: 'Placeholder for Ten of Swords' },
    { name: 'Page of Swords', image: 'Placeholder for Page of Swords' },
    { name: 'Knight of Swords', image: 'Placeholder for Knight of Swords' },
    { name: 'Queen of Swords', image: 'Placeholder for Queen of Swords' },
    { name: 'King of Swords', image: 'Placeholder for King of Swords' },
    // Cups
    { name: 'Ace of Wands', image: 'Placeholder for Ace of Wands' },
    { name: 'Two of Wands', image: 'Placeholder for Two of Wands' },
    { name: 'Three of Wands', image: 'Placeholder for Three of Wands' },
    { name: 'Four of Wands', image: 'Placeholder for Four of Wands' },
    { name: 'Five of Wands', image: 'Placeholder for Five of Wands' },
    { name: 'Six of Wands', image: 'Placeholder for Six of Wands' },
    { name: 'Seven of Wands', image: 'Placeholder for Seven of Wands' },
    { name: 'Eight of Wands', image: 'Placeholder for Eight of Wands' },
    { name: 'Nine of Wands', image: 'Placeholder for Nine of Wands' },
    { name: 'Ten of Wands', image: 'Placeholder for Ten of Wands' },
    { name: 'Page of Wands', image: 'Placeholder for Page of Wands' },
    { name: 'Knight of Wands', image: 'Placeholder for Knight of Wands' },
    { name: 'Queen of Wands', image: 'Placeholder for Queen of Wands' },
    { name: 'King of Wands', image: 'Placeholder for King of Wands' },
];

export default tarotCards;